### PR TITLE
appease the cops

### PR DESCRIPTION
**Pull request by majormoses**
#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### Purpose
Appease the cops and get CI passing.

### CODE REVIEW

**Comment by majormoses** [comment]
@scosist can I get you do some regression testing on this to make sure nothing broke? There should not be...

**Comment by majormoses** [comment]
looks like still more changes before CI passes.

**Comment by majormoses** [comment]
@eheydrick @mattyjones not sure I have enough access to solve this: https://travis-ci.org/sensu-plugins/sensu-plugins-nrpe/jobs/230668858#L255

**Comment by scosist** [comment]
@majormoses I did some quick testing on your changes in this branch, looks to work as it did before. However, I couldn't build without #5.

**Comment by eheydrick** [comment]
I just updated the gemspec and a few other things in the skel files. Namely removed the cert stuff, which isn't used anymore. Make those changes here and it should start building.

**Comment by majormoses** [comment]
@eheydrick thanks I have done that once I validate that this is fixed here I will do the same to the other 2 repos I created.

**Pull request merged**
